### ISSUE TITLE
Strange appVersion:

### ISSUE THREAD

**Issue by evgkrsk** [startxfr/helm-repository#3]
**Describe the bug**
"helm ls" give strange output with recent version of project chart:

**To Reproduce**
1. helm install production startx/project  --version 10.12.41
2. helm ls
3. See strange appversion

**Given behavior**
```
production                      default         1               2022-06-25 18:57:47.745273 +0700 +07    deployed        project-10.12.41                        4.10.12{{ $root.Values.kraken.cerberusUrl | quote }}
```
**Expected behavior**
```
production                      default         1               2022-06-25 18:57:47.745273 +0700 +07    deployed        project-10.12.41                        4.10.12
```

**Comment by startxfr** [comment]
Hi @evgkrsk, thanks for this report. A bad search/replace break our appVersion in Chart.yaml. 

New release of chart is under build and is now released. You can target the good release [10.12.71](https://github.com/startxfr/helm-repository/releases/tag/10.12.71) if you want to have this bug removed. 
You can also update your repository with `helm repo update`.

Many thanks for your contribution ;)
