### ISSUE TITLE
Cluster-Auth

### ISSUE THREAD

**Issue by shios86** [startxfr/helm-repository#8]
**Is your feature request related to a problem? Please describe.**
HTML must be included in the repository, and for each difference those too must be included in the repository

**Describe the solution you'd like**
A variable to include inlined HTML for providers, login and errors (cluster auth)

**Additional context**
Helps for ansible-sxcm

**Comment by startxfr** [comment]
available since 4 month https://github.com/startxfr/helm-repository/commit/897f2c7ca73d5aa7110ddd44073fbe5dfe1ad256
